#!/bin/bash

# GLP - Entity Referential Error
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.2 --num_anns 5 --dataset_root dataset/Entity_Referential_Error_noise_5error_MSCOCO --noise_file annotations/scan_split/0.2_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Entity_Referential_Error_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.4 --num_anns 5 --dataset_root dataset/Entity_Referential_Error_noise_5error_MSCOCO --noise_file annotations/scan_split/0.4_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Entity_Referential_Error_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.6 --num_anns 5 --dataset_root dataset/Entity_Referential_Error_noise_5error_MSCOCO --noise_file annotations/scan_split/0.6_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Entity_Referential_Error_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 1.0 --num_anns 5 --dataset_root dataset/Entity_Referential_Error_noise_5error_MSCOCO --noise_file annotations/scan_split/1.0_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Entity_Referential_Error_5error_models --device 0

# GLP - Object Omission
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.2 --num_anns 5 --dataset_root dataset/Object_Omission_noise_5error_MSCOCO --noise_file annotations/scan_split/0.2_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Object_Omission_noise_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.4 --num_anns 5 --dataset_root dataset/Object_Omission_noise_5error_MSCOCO --noise_file annotations/scan_split/0.4_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Object_Omission_noise_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.6 --num_anns 5 --dataset_root dataset/Object_Omission_noise_5error_MSCOCO --noise_file annotations/scan_split/0.6_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Object_Omission_noise_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 1.0 --num_anns 5 --dataset_root dataset/Object_Omission_noise_5error_MSCOCO --noise_file annotations/scan_split/1.0_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Object_Omission_noise_5error_models --device 0

# GLP - Short Description
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.2 --num_anns 5 --dataset_root dataset/Short_Description_noise_5error_MSCOCO --noise_file annotations/scan_split/0.2_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Short_Description_noise_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.4 --num_anns 5 --dataset_root dataset/Short_Description_noise_5error_MSCOCO --noise_file annotations/scan_split/0.4_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Short_Description_noise_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.6 --num_anns 5 --dataset_root dataset/Short_Description_noise_5error_MSCOCO --noise_file annotations/scan_split/0.6_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Short_Description_noise_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 1.0 --num_anns 5 --dataset_root dataset/Short_Description_noise_5error_MSCOCO --noise_file annotations/scan_split/1.0_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/Short_Description_noise_5error_models --device 0

# GLP - High level Semantic Confusion
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.2 --num_anns 5 --dataset_root dataset/High_level_Semantic_Confusion_5error_MSCOCO --noise_file annotations/scan_split/0.2_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/High_level_Semantic_Confusion_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.4 --num_anns 5 --dataset_root dataset/High_level_Semantic_Confusion_5error_MSCOCO --noise_file annotations/scan_split/0.4_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/High_level_Semantic_Confusion_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 0.6 --num_anns 5 --dataset_root dataset/High_level_Semantic_Confusion_5error_MSCOCO --noise_file annotations/scan_split/0.6_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/High_level_Semantic_Confusion_5error_models --device 0
python main_GLP_queue_ema.py --batch_size 256 --epochs 5 --lr 5e-7 --vision_model ViT-B/32 --noise_ratio 1.0 --num_anns 5 --dataset_root dataset/High_level_Semantic_Confusion_5error_MSCOCO --noise_file annotations/scan_split/1.0_noise_aware_train_caps.txt --dataset coco --checkpoint_path MSCOCO_models/GLP_queue/High_level_Semantic_Confusion_5error_models --device 0